# 策略参数
min_pos: 0.0
max_pos: 1.0
commission: 0.0003 #手续费
fix_weight: 1.0  # 基线权重

# 模型参数
hidden_dim: 128
n_layers: 2

# 训练参数
lr: 0.0001
gamma: 0.99
gae_lambda: 0.95
clip_eps: 0.2
batch_size: 64
n_epochs: 60
buffer_size: 1024
patience: 20